version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true # 初期構築時にコンテナを常駐させるよう一時対応
    stdin_open: true # 初期構築時にコンテナを常駐させるよう一時対応

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    volumes:
      - ./backend:/app
    tty: true # 初期構築時にコンテナを常駐させるよう一時対応
    stdin_open: true # 初期構築時にコンテナを常駐させるよう一時対応

  db:
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
