FROM golang:1.22.3-alpine

WORKDIR /app

COPY scripts/init.sh /usr/local/bin/init.sh

RUN chmod +x /usr/local/bin/init.sh

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
