openapi: '3.0.3'

info:
  title: reversi-app
  version: 1.0.0

paths:
  /signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: username123
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: P@ssw0rd
      responses:
        201:
          description: User Created
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: P@ssw0rd
      responses:
        200:
          description: Return JWT token
  /logout:
    post:
      responses:
        200:
          description: Clear Cookie
  /csrf:
    get:
      responses:
        200:
          description: Get Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  csrf_token:
                    type: string
                    example: token
  /check-auth:
    get:
      responses:
        200:
          description: Get Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_login:
                    type: boolean
                    example: true
                  user_id:
                    type: integer
                    example: 1

  /games:
    get:
      responses:
        200:
          description: Get Game History
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        winner_user:
                          type: string
                          example: winner_username
                        winner_disc:
                          type: integer
                          example: 1
                        lose_user:
                          type: string
                          example: lose_username
                        started_at:
                          type: string
                          example: 2024-06-21T17:32:28z
                        end_at:
                          type: string
                          example: 2024-06-21T17:53:52z
    post:
      responses:
        200:
          description: Create new game and return game_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  game_id:
                    type: integer
                    example: 1

  /games/latest/turns/{game_id}:
    parameters:
      - name: game_id
        in: path
        schema:
          type: integer
        required: true
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  game_id:
                    type: integer
                    example: 1
                  turn_count:
                    type: integer
                    example: 1
                  board:
                    type: array
                    example:
                      [
                        [0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,0,0,0],
                        [0,0,0,1,2,0,0,0],
                        [0,0,0,2,1,0,0,0],
                        [0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,0,0,0],
                        [0,0,0,0,0,0,0,0]
                      ]
                  next_disc:
                    type: integer
                    example: 2
                  winner_disc:
                    type: integer
                    example: 0

  /games/latest/turns:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                game_id:
                  type: integer
                  example: 1
                turn_count:
                  type: integer
                  example: 1
                move:
                  type: object
                  properties:
                    disc:
                      type: integer
                      example: 1
                    x:
                      type: integer
                      example: 1
                    y:
                      type: integer
                      example: 1
      responses:
        201:
          description: Created
